name: Dumping

on:
  workflow_dispatch:
    inputs:
      rom_link:
        description: 'rom link'
        required: true

env:
  ROM_URL: ${{ github.event.inputs.rom_link }}
jobs:
  dump:
    runs-on: ubuntu-22.04

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clone Dumper Source Code
         run: git clone https://github.com/MinatiScape/phoenix_firmware_dumper dumper --depth=1
       
       - name: Setting up Dumper requirements
         run: |
              sudo chmod -R 777 dumper
              cd dumper
              sudo pip3 install wheel setuptools
              sudo bash setup.sh
              touch .tg_token
              echo "${{ secrets.BOT }}" >> ".tg_token"
              touch .github_orgname
              echo "MinatiScape" >> ".github_orgname"
              touch .github_token
              echo "${{ secrets.GHTOKEN }}" >> ".github_token"
              touch .tg_chat
              echo "@minati_dumps" >> ".tg_chat"
              git config --global user.email "sinha.aryan03@gmail.com"
              git config --global user.name "techyminati"
       - name: Download Stock Rom & Generate dump
         run: |
              cd dumper
              sudo apt install neofetch -y
              sudo git config --global user.email "you@example.com"
              sudo git config --global user.name "Your Name"
              # export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python
              sudo bash dumper.sh $ROM_URL
